import 'student.dart';

List<Map<String, dynamic>> studentJsonData = [
  {"id": "653450086-7", "firstName": "จารุวิทย์", "lastName": "แสงแก้วสิริกุล", "gender": "male", "imageUrl": "assets/male1.jpg"},
  {"id": "653450087-5", "firstName": "ชวกร", "lastName": "เนืองภา", "gender": "male", "imageUrl": "assets/male2.jpg"},
  {"id": "653450088-3", "firstName": "ณัฐดนัย", "lastName": "ภาคภูมิ", "gender": "male", "imageUrl": "assets/male3.jpg"},
  {"id": "653450089-1", "firstName": "ณัฐวรรณ", "lastName": "พวงมะลัย", "gender": "female", "imageUrl": "assets/female1.jpg"},
  {"id": "653450090-6", "firstName": "ถิรวัฒน์", "lastName": "โชติธนกิจไพศาล", "gender": "male", "imageUrl": "assets/male4.jpg"},
  {"id": "653450091-4", "firstName": "เทพฤทธิ์", "lastName": "อินทรประพันธ์", "gender": "male", "imageUrl": "assets/male5.jpg"},
  {"id": "653450092-2", "firstName": "ธนาพร", "lastName": "ชนิดกุล", "gender": "male", "imageUrl": "assets/male6.jpg"},
  {"id": "653450094-8", "firstName": "นันทิพัฒน์", "lastName": "บุตรวัง", "gender": "male", "imageUrl": "assets/male7.jpg"},
  {"id": "653450095-6", "firstName": "พิชชากร", "lastName": "สกุลไทย", "gender": "male", "imageUrl": "assets/male8.jpg"},
  {"id": "653450096-4", "firstName": "พิชัย", "lastName": "ทองอาสา", "gender": "male", "imageUrl": "assets/male9.jpg"},
  {"id": "653450097-2", "firstName": "พิพิธธน", "lastName": "พิพิธกุล", "gender": "male", "imageUrl": "assets/male10.jpg"},
  {"id": "653450098-0", "firstName": "พิริยกร", "lastName": "พันธุ์พานิชย์", "gender": "male", "imageUrl": "assets/male11.jpg"},
  {"id": "653450099-8", "firstName": "ภานุวัฒน์", "lastName": "ธรรมบุตร", "gender": "male", "imageUrl": "assets/male12.jpg"},
  {"id": "653450100-9", "firstName": "เมธากร", "lastName": "สิงห์คาน", "gender": "male", "imageUrl": "assets/male13.jpg"},
  {"id": "653450101-7", "firstName": "วงศธร", "lastName": "ทองอินทร์", "gender": "male", "imageUrl": "assets/male14.jpg"},
  {"id": "653450103-3", "firstName": "วิชญ์พล", "lastName": "ยืนยง", "gender": "male", "imageUrl": "assets/male15.jpg"},
  {"id": "653450104-1", "firstName": "ศานต์ฤทัย", "lastName": "สายบุตร", "gender": "female", "imageUrl": "assets/female2.jpg"},
  {"id": "653450106-7", "firstName": "อนิวัตติ์", "lastName": "ณ หนองคาย", "gender": "male", "imageUrl": "assets/male16.jpg"},
  {"id": "653450107-5", "firstName": "อรปรียา", "lastName": "จันทะโคตร", "gender": "female", "imageUrl": "assets/female3.jpg"},
  {"id": "653450108-3", "firstName": "อัครวิชญ์", "lastName": "พบวงษา", "gender": "male", "imageUrl": "assets/male17.jpg"},
  {"id": "653450279-6", "firstName": "กฤตชวกร", "lastName": "ชวลิตกิตติวงศ์", "gender": "male", "imageUrl": "assets/male18.jpg"},
  {"id": "653450280-1", "firstName": "จันทิมา", "lastName": "พรมวัง", "gender": "female", "imageUrl": "assets/female4.jpg"},
  {"id": "653450281-9", "firstName": "ชฎาพร", "lastName": "พินิจสัย", "gender": "female", "imageUrl": "assets/female5.jpg"},
  {"id": "653450282-7", "firstName": "ณภัทร", "lastName": "สุยังกุล", "gender": "male", "imageUrl": "assets/male19.jpg"},
  {"id": "653450283-5", "firstName": "ณัฏฐกิตติ์", "lastName": "มิตรสูงเนิน", "gender": "male", "imageUrl": "assets/male20.jpg"},
  {"id": "653450284-3", "firstName": "ณัฐณิชา", "lastName": "พรมปิก", "gender": "female", "imageUrl": "assets/female6.jpg"},
  {"id": "653450285-1", "firstName": "ธนกร", "lastName": "สว่างสูงเนิน", "gender": "male", "imageUrl": "assets/male21.jpg"},
  {"id": "653450286-9", "firstName": "ธนพร", "lastName": "รัตนศิระประภา", "gender": "female", "imageUrl": "assets/female7.jpg"},
  {"id": "653450287-7", "firstName": "ธนาโชค", "lastName": "สุวรรณ์", "gender": "male", "imageUrl": "assets/male22.jpg"},
  {"id": "653450288-5", "firstName": "ธีร", "lastName": "ริ้วทวี", "gender": "male", "imageUrl": "assets/male23.jpg"},
  {"id": "653450290-8", "firstName": "นภสินธุ์", "lastName": "ศรีบุรินทร์", "gender": "male", "imageUrl": "assets/male24.jpg"},
  {"id": "653450291-6", "firstName": "นันธวัฒน์", "lastName": "แผ่ความดี", "gender": "male", "imageUrl": "assets/male25.jpg"},
  {"id": "653450292-4", "firstName": "เนติธร", "lastName": "ศรีมี", "gender": "male", "imageUrl": "assets/male26.jpg"},
  {"id": "653450293-2", "firstName": "ปฏิพัทธ์", "lastName": "มาตรา", "gender": "male", "imageUrl": "assets/male27.jpg"},
  {"id": "653450294-0", "firstName": "ประจักษ์", "lastName": "ศรีทอง", "gender": "male", "imageUrl": "assets/male29.jpg"},
  {"id": "653450295-8", "firstName": "ภานุวัฒน์", "lastName": "สารวงษ์", "gender": "male", "imageUrl": "assets/male28.jpg"},
  {"id": "653450296-6", "firstName": "มหัคฆพันธ์", "lastName": "ปลั่งกลาง", "gender": "male", "imageUrl": "assets/male30.jpg"},
  {"id": "653450297-4", "firstName": "รามิล", "lastName": "ไกยบุตร", "gender": "female", "imageUrl": "assets/female8.jpg"},
  {"id": "653450298-2", "firstName": "วรชิต", "lastName": "ทองเลิศ", "gender": "male", "imageUrl": "assets/male31.jpg"},
  {"id": "653450299-0", "firstName": "วรโชติ", "lastName": "ทองเลิศ", "gender": "male", "imageUrl": "assets/male32.jpg"},
  {"id": "653450300-1", "firstName": "ฮารูณ", "lastName": "ซิดดิ๊ก คูเรซิ", "gender": "male", "imageUrl": "assets/male33.jpg"},
  {"id": "653450507-9", "firstName": "ชาคริต", "lastName": "พูลพิพิธ", "gender": "male", "imageUrl": "assets/male34.jpg"},
  {"id": "653450508-7", "firstName": "ณภัทร", "lastName": "สีหะวงค์", "gender": "male", "imageUrl": "assets/male35.jpg"},
  {"id": "653450509-5", "firstName": "ทวีศิลป์", "lastName": "ใจดี", "gender": "male", "imageUrl": "assets/male36.jpg"},
  {"id": "653450510-0", "firstName": "นันทวัฒน์", "lastName": "แซ่ฮวม", "gender": "male", "imageUrl": "assets/male37.jpg"},
  {"id": "653450513-4", "firstName": "ศิริพร", "lastName": "แก้วลินลา", "gender": "female", "imageUrl": "assets/female9.jpg"},
];

List<Student> studentList = studentJsonData.map((data) => Student(
  id: data['id'],
  firstName: data['firstName'],
  lastName: data['lastName'],
  gender: data['gender'],
  imageUrl: data['imageUrl'],
)).toList();